-- vim.keymap.set("n", "<leader>ff", ":GFiles<CR>", {})
-- vim.keymap.set("n", "<leader>ps", ":Rg<CR>", {})
-- vim.keymap.set("n", "<leader>lb", ":Buffers<CR>", {})

local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>ps", builtin.live_grep, {})
vim.keymap.set("n", "<leader>lb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>ld", builtin.diagnostics, {})
vim.keymap.set("n", "<leader>lr", builtin.lsp_references, {})
