vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.hidden = false
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.hlsearch = true
vim.opt.incsearch = false
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.updatetime = 300
vim.cmd([[set undodir=$HOME/.undodir]])
vim.opt.undofile = true
vim.opt.signcolumn = "yes"
vim.opt.ignorecase = true
vim.opt.showmode = false
vim.opt.colorcolumn = "80"
-- For enabling mouse ("a" - on / "" - off):
vim.opt.mouse = "a"
-- vim.opt.smartcase = true
