vim.opt.nu = true
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.smartindent=true
vim.opt.wrap=false
vim.opt.swapfile=false
vim.opt.backup=false
vim.opt.hlsearch=false
vim.opt.incsearch=false
vim.opt.termguicolors=true
vim.opt.scrolloff=8
vim.opt.updatetime=50
vim.cmd[[set undodir=$HOME/.undodir]]
vim.opt.undofile=true
